# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title rwMCpp
#' @description A Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param sigma variance
#' @param x0 the initial value
#' @return random walk samples
#' @examples
#' \dontrun{
#' rnC <- rwMCpp(1, 20, 1000)
#' plot(rnC)
#' }
#' @export


